name: Multiple jobs Workflow
on:
  workflow_dispatch:
jobs:
  network-job: 
    runs-on: ubuntu-latest 
    steps:
      - name: IP address
        run: ip a 
      - name: google dns
        run:  curl -I https://microsoft.com
  info-job: 
    runs-on: ubuntu-latest
    steps:
      - name: show Date
        run: date
      - name: show current user
        run: whoami
  build-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Build steps
        run: | 
          echo "Building application..."
          sleep 10
          echo "Build Completed"
  deploy-job:
    needs: build-job 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy steps
        run:  echo "Deploying application..."

  
