name: Multiple jobs Workflow
on:
  push:
    branches:
      - main
jobs:
  network-job: 
    runs-on: ubuntu-latest 
    steps:
      - name: IP address
        run: ip a 
      - name: google dns
        run: ping -c 4 google.com
  info-job: 
    runs-on: ubuntu-latest
    steps:
      - name: show Date
        run: date
      - name: show current user
        run: whoami
  
